disabled_rules:
  - valid_docs
included: # paths to include during linting. `--path` is ignored if present.
  - NimbleRAC
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage

line_length: 130
type_body_length:
  error: 300
file_length:
  error: 500
type_name:
  min_length: 3
  max_length: 40
variable_name:
  min_length: 3
reporter: "xcode"
