# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
language: objective-c
osx_image: xcode7.2
notifications:
  email: false
install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - carthage bootstrap --platform ios
script:
  - set -o pipefail && xcodebuild test -project NimbleRAC.xcodeproj -scheme NimbleRAC -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' ONLY_ACTIVE_ARCH=NO | xcpretty -c
